### ISSUE TITLE
Error while using multiple Sub Apps

### ISSUE THREAD

**Issue by T4LO5** [lukeed/polka#56]
```js
/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:99
                let loop = _ => res.finished || (i < len) ? arr[i++](req, res, next) : fn(req, res);
                                                                    ^

TypeError: arr[(i++)] is not a function
    at loop (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:99:55)
    at next (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:98:63)
    at Array.arr.push (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:54:69)
    at loop (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:99:55)
    at next (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:98:63)
    at Array.jsonParser (/Users/**/Documents/Node.js/Bot List Final/node_modules/body-parser/lib/types/json.js:110:7)
    at loop (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:99:55)
    at Polka.handler (/Users/**/Documents/Node.js/Bot List Final/node_modules/polka/index.js:100:3)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

Upon using multiple sub apps, this error is thrown. If only 1 sub app is used the functionality works as expected.

**Comment by lukeed** [comment]
I know this error message is kinda useless, but what it typically means is that one of your sub-apps' functions had a syntax error or something like that.

If the sub-app you commented out allowed it to work, walk thru that grouping carefully.

Multiple sub-apps very much works :) For example, my work production server is compromised of nearly 40 sub applications.

**Comment by T4LO5** [comment]
Do you see something wrong here that i am missing ?

```javascript
const polka = require("polka");

const utilRouter = polka()
.get("/ping", async ( req, res ) => {
  res.end(JSON.stringify({ping: Math.floor(Math.random() * 11)}))
})

module.export = { utilRouter }
```
Throws the same error when i go to /util/ping

**Comment by lukeed** [comment]
How are you importing this file into your main app?

Also, I'm pretty sure the spacing here is parsed incorrectly. It throws for me trying to run it, as is, on its own. Try this:

```js
const polka = require("polka");

const utilRouter = polka();

utilRouter.get("/ping", async ( req, res ) => {
  res.end(JSON.stringify({ping: Math.floor(Math.random() * 11)}))
})

module.export = { utilRouter }
```

**Comment by T4LO5** [comment]
Same error and from my main file
```javascript
const { utilRouter } = require("./routes/util.route");

//Initiate App
.use("/util", utilRouter)
.listen(3000).then( _ => {
  console.log(`> Running on localhost:3000`);
});
```

**Comment by T4LO5** [comment]
Update directly attaching that exact route to the app in the main final results in it working perfectly.

**Comment by lukeed** [comment]
Found the issue.

As mentioned, it's a vague error message, but that's because Polka doesn't evaluate subapps on require.

```
module.export = { utilRouter }
```

...should be `module.exports`

This doesn't throw as a syntax error because `module` is a global object, and you're creating a new key named `export`, haha. So, on the `require` side, it's pulling in `utilRouter = undefined`, which is not a function. 😄

**Comment by T4LO5** [comment]
That was such a rookie mistake 🙈 , thanks for all your help.

**Comment by lukeed** [comment]
Haha no problem, happens to all of us
